# Generated by Django 6.0.1 on 2026-07-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Clean Lines. Conscious Living.', max_length=200)),
                ('subtitle', models.CharField(default='Timeless essentials for the modern minimalist. Designed to simplify your wardrobe.', max_length=300)),
                ('image', models.ImageField(help_text='Upload background image for the slide', upload_to='hero_slides/')),
                ('order', models.IntegerField(default=0, help_text='Sorting order in the carousel')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
